### ISSUE TITLE
Support for 1.20.6?

### ISSUE THREAD

**Issue by mrpf-me** [Yronusa2000/Sauron#1]
Unfortunately, an error occurs when remapping the plugin from papermc.
SaveNBT does not seem to be recognised. When I install SaveNBT manually, I get many errors.

Startup Error without SafeNBT:
```
[05:09:23 ERROR]: [ModernPluginLoadingStrategy] Could not load 'plugins/.paper-remapped/Sauron-1.2.2.jar' in 'plugins/.paper-remapped'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [SafeNBT]. Please download and install these plugins to run 'Sauron'.
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:82) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:510) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:286) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Trying to add Item:
```
[05:17:23 INFO]: Pfandleiher issued server command: /sauron track
[05:17:23 ERROR]: Command exception: /sauron track
org.bukkit.command.CommandException: Unhandled exception executing command 'sauron' in plugin Sauron v1.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:86) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class fr.yronusa.sauron.SafeNBTAPI.SafeNBT
        at Sauron-1.2.2.jar/fr.yronusa.sauron.ItemMutable.hasTrackingID(ItemMutable.java:114) ~[Sauron-1.2.2.jar:?]
        at Sauron-1.2.2.jar/fr.yronusa.sauron.Commands.Command.track(Command.java:105) ~[Sauron-1.2.2.jar:?]
        at Sauron-1.2.2.jar/fr.yronusa.sauron.Commands.Command.onCommand(Command.java:52) ~[Sauron-1.2.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 26 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3 [in thread "Server thread"]
        at Sauron-1.2.2.jar/fr.yronusa.sauron.SafeNBTAPI.SafeNBT.<clinit>(SafeNBT.java:33) ~[Sauron-1.2.2.jar:?]
        at Sauron-1.2.2.jar/fr.yronusa.sauron.ItemMutable.hasTrackingID(ItemMutable.java:114) ~[Sauron-1.2.2.jar:?]
        at Sauron-1.2.2.jar/fr.yronusa.sauron.Tracker.execute(Tracker.java:37) ~[Sauron-1.2.2.jar:?]
        at Sauron-1.2.2.jar/fr.yronusa.sauron.Tracker.trackHandledItems(Tracker.java:68) ~[Sauron-1.2.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor295.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-124-0fcf3e3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleSetCarriedItem(ServerGamePacketListenerImpl.java:2116) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:33) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.network.protocol.game.ServerboundSetCarriedItemPacket.handle(ServerboundSetCarriedItemPacket.java:15) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-124-0fcf3e3]
        ... 13 more
```

I am aware that the currently supported version is `1.12-1.19`. 
Does the 1.20 have higher challenges that make it difficult for the plugin to be compatible?

The concept of this plugin is great, I have been looking for it for a long time.
Will there be a port to 1.20.6 in the near future?

**Comment by mrpf-me** [comment]
I tried using SaveNBT standalone.
It seems that this is generally not supported.
This is bad, especially if Sauron is built upon it.

You could possibly switch to NBTEdit (actively supported)
https://github.com/tr7zw/Item-NBT-API

**Comment by yro7** [comment]
Hey,

Thanks you for the report and sorry for the inconvenience.

As you said, SafeNBT does not support 1.20.6 and so do not Sauron. Switching to NBTEdit is a great idea, let me 2 or 3 days and it will be done :) 

That said, I need to warn you : Sauron is unstable, especially if the tracked items often get their NBT changed by other plug-ins. On my 1.12.2 server, I couldn't make it work on those types of item. I'm looking forward to fix that but to be honest I couldn't figure what's wrong for now. You should be cautious before putting the plug-in in production.

**Comment by yro7** [comment]
Hey,

Thanks you for the report and sorry for the inconvenience.

As you said, SafeNBT does not support 1.20.6 and so do not Sauron. Switching to NBTEdit is a great idea, let me 2 or 3 days and it will be done :)

That said, I need to warn you : Sauron is unstable, especially if the tracked items often get their NBT changed by other plug-ins. On my 1.12.2 server, I couldn't make it work on those types of item. I'm looking forward to fix that but to be honest I couldn't figure what's wrong for now. You should be cautious before putting the plug-in in production.

**Comment by yro7** [comment]
(My bad, closed by error)

**Comment by mrpf-me** [comment]
Hey, thanks for the quick feedback.

Yeah, I almost thought so, I'm glad you're considering changing the API. I think you'll be better off in the future.

I don't have a production-ready system at the moment, but I'm preparing everything and looking for unique plugins to ensure a high fun factor but also security.

My team and I would like to test Sauron on the development system and then give you feedback and test for bugs.

Looking forward to the next update!

**Comment by yro7** [comment]
Hey,

So I switched the API's, you should do fine, however I still have some issue, like with config which gets reset every time the plug-in reloads, I'm fixing this. 
Except that everything should be okay.

**Comment by mrpf-me** [comment]
Awesome! As soon as this is fixed, could you post a release here? Alternatively on Spigot, but Github is better for testing.

**Comment by yro7** [comment]
Sure no problem!

Just by curiosity, what are you planning to use Sauron for? Refunds, tracking or anti duplication?

**Comment by mrpf-me** [comment]
I think the idea of being able to track items is pretty cool, but refunds are also interesting. In the past, players have said that they've lost items, and this would be a way to prevent duplicates after staff issued refunds.
Feel free to send me a friend request on Discord: `pfandleiher`

**Comment by yro7** [comment]
Sauron now supports 1.20.6, thanks for the report.
